languages = {
	'Python': {'description': 'Python is a modern, interpreted, high-level and general-purpose programming language. Its design philosophy emphasizes code readability. Python was created in 1991, and it is now the most popular programming language in the world, even more than Java. Python is mainly used by data scientists.' , 'resources':['https://cscircles.cemc.uwaterloo.ca/' , 'https://www.codecademy.com/learn/learn-python' , 'https://www.learnpython.org/' , 'https://www.youtube.com/watch?v=_uQrJ0TkZlc&vl=en' , 'https://online-learning.harvard.edu/subject/python' , 'https://www.w3schools.com/python/default.asp']},
	'Java': {'description': 'Java is a concurrent, class-based, statistically typed object-oriented language. It was released in 1996 and quickly became the most popular language in the world and stayed there for about 2 decades. It remains very popular to this day, being only beaten by Python. Java is mainly used in big enterprises, thanks to its easy-to-read syntax.' , 'resources': ['https://www.codecademy.com/learn/learn-java' , 'https://www.learnjavaonline.org/' , 'https://www.w3schools.com/java/default.asp' , 'https://docs.oracle.com/javase/tutorial/java/index.html'  , 'https://www.youtube.com/watch?v=eIrMbAQSU34' , 'https://www.programiz.com/java-programming']},
	'Javascript': {'description': 'Created in 1995, JavaScript was originally called LiveScript. Along with HTML and CSS, JavaScript makes up the web.' , 'resources': ['https://www.codecademy.com/learn/introduction-to-javascript' , 'https://www.w3schools.com/js/DEFAULT.asp' , 'https://javascript.info/' , 'https://www.learn-js.org/' , 'https://www.youtube.com/watch?v=W6NZfCO5SIk' , 'https://online-learning.harvard.edu/subject/javascript' , 'https://www.khanacademy.org/computing/computer-programming/programming']},
	'C': {'description': 'C is a low-level and cross-platform imperative language which was created in 1972. C is used for scripting system applications which form a major part of windows, UNIX, and Linux.' , 'resources': ['https://www.learn-c.org/' , 'https://www.programiz.com/c-programming' , 'https://www.cprogramming.com/tutorial/c-tutorial.html?inl=nv' , 'https://www.edx.org/learn/c-programming' , 'https://online-learning.harvard.edu/subject/c' , 'https://www.youtube.com/watch?v=gfkTfcpWqAY' , 'https://www.coursera.org/learn/c-for-everyone']},
	'C++': {'description': 'Created in 1998 by Bjarne Stroustrup. C++ is a general-purpose programming language created as an extension of the C programming language. It can be thought of as "C with Classes". C++ is useful for building real-time, image processing, mobile sensor applications, visual effects, and modeling.' , 'resources': ['https://www.codecademy.com/learn/learn-c-plus-plus' , 'https://www.w3schools.com/cpp/' , 'https://www.programiz.com/cpp-programming', 'https://www.edx.org/learn/c-plus-plus', 'https://www.learn-cpp.org/' , 'https://www.edx.org/course/introduction-to-c-3' , 'https://www.youtube.com/watch?v=NxS_0vR-PPg' , 'https://www.cplusplus.com/doc/tutorial/']},
	'C#': {'description': 'C# is similar to Java and it was created by Microsoft in the year 2000. C# is primarily used on the Windows . NET framework, although it can be applied to an open source platform too.', 'resources': ['https://www.codecademy.com/learn/learn-c-sharp' , 'https://dotnet.microsoft.com/learn/csharp' , 'https://www.w3schools.com/cs/' , 'https://www.learncs.org/' , 'https://www.edx.org/learn/c-sharp' , 'https://www.youtube.com/watch?v=gfkTfcpWqAY' , 'https://online-learning.harvard.edu/subject/programming']},
	'Haskell': {'description': 'Haskell is a general-purpose, statically typed, purely functional programming language with type inference created in 1990. Haskell is mainly suited for proprietary business logic and data analysis, and fast prototyping and enhancing existing software environments with correct code.' , 'resources': ['http://learnyouahaskell.com/introduction' , 'https://learnxinyminutes.com/docs/haskell/' , 'https://www.tutorialspoint.com/haskell/index.htm' , 'https://www.youtube.com/watch?v=02_H3LjqMr8']},
	'BASIC': {'description': 'Created in the 1960s, BASIC is a fairly old programming language and consists of a family of general-purpose, high-level programming languages whose design philosophy emphasizes ease of use.' , 'resources': ['http://www.hoist-point.com/applesoft_basic_tutorial.htm' , 'https://www.youtube.com/watch?v=dwVAR6HClmI']},
	'Rust':{'description': 'Rust is a multi-paradigm programming language designed for performance and safety. Rust is syntactically similar to C++, making it easy to understand. It was created in 2010 and is used for creating game engines, operating systems, and file systems.'  , 'resources': ['https://www.rust-lang.org/learn' , 'https://learning-rust.github.io/' , 'https://www.youtube.com/watch?v=zF34dRivLOw']}
}
